### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by ekagrashukla** [ekagrashukla/Covictory-twitter_search_for_Covid19#1]
Currently COVICTORY uses Foundation by Zurb for the User Interface. It would be great if someone could make it much more minimal and improve the user experience.

**Comment by godwin-morwin** [comment]
hi, I do like to work on this issue

**Comment by ekagrashukla** [comment]
Thanks @Godwindaniel10 
Please continue with the work, and once done create a pull request.

**Comment by godwin-morwin** [comment]
great, on it ..
